# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTeiKLl_tcE2gvC77uEk97Wt63cUMZi1
"""

!pip install -q -U google-genai
from google.genai import client
MY_API_KEY = ""YOUR_GEMINI_API_KEY""
ai_bot = client.Client(api_key=MY_API_KEY)
response = ai_bot.models.generate_content(model='gemini-3.6-flash', contents='안녕!')
print(response.text)

!pip install -q -U duckduckgo-search
from duckduckgo_search import DDGS
def search_web(query: str) -> str:
    """인터넷에서 최신 뉴스 및 정보를 검색합니다."""
    results = []
    with DDGS() as ddgs:
        for r in ddgs.text(query, max_results=3):
            results.append(f"제목: {r['title']}\n내용: {r['body']}\n링크: {r['href']}")
    return "\n\n".join(results)
company_name = "HD현대중공업 조선 사업부 주요 협력사" # 원하는 기업명으로 변경 가능
prompt = f"""
당신은 HD현대중공업 동반성장팀의 리스크 관리 담당 에이전트입니다.
'{company_name}' 관련 최신 동향과 리스크(ESG, 원자재 가격, 중대재해, 노사관계 등)를 웹 검색 도구를 사용해 탐색하세요.
수집된 정보를 바탕으로 아래 양식에 맞추어 실무 보고서를 작성하세요:
1. 최근 주요 이슈 요약 (3줄)
2. 동반성장 관점에서의 잠재적 위험 요인
3. HD현대중공업 차원의 지원 및 대응 방안 제안
"""
response = ai_bot.models.generate_content(
    model='gemini-3.6-flash',
    contents=prompt,
    config={'tools': [search_web]} )
print(response.text)

!pip install -q -U google-genai
import smtplib
import pandas as pd
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os
import google.generativeai as genai # Import the new generativeai library

# -------------------------------------------------------------
# 1. 발송자 설정 (본인 정보 입력)
# -------------------------------------------------------------
SENDER_EMAIL = "naseunga03@gmail.com"        # 보내는 지메일
SENDER_PASSWORD = "fuym yqxo vwdb bgfy"       # 16자리 앱 비밀번호
RECEIVER_EMAIL = "naseunga03@naver.com"      # 테스트용 결과를 받아볼 본인 메일 주소

# API Key configuration for Google Generative AI
# Assuming MY_API_KEY is available from previous setup or environment variables.
# For demonstration, hardcoding it here as it was in the prior setup cell.
MY_API_KEY = ""YOUR_GEMINI_API_KEY""
genai.configure(api_key=MY_API_KEY)

# -------------------------------------------------------------
# 2. '담당자_명단.csv' 파일 자동 생성
# -------------------------------------------------------------
contacts_data = {
    "부서명": ["동반성장팀", "구매자재팀", "안전보건팀"],
    "담당자": ["김철수 팀장", "이영희 대리", "박민수 과장"],
    "이메일": [RECEIVER_EMAIL, RECEIVER_EMAIL, RECEIVER_EMAIL], # 본인 메일로 받아서 확인
    "수신조건": ["모든리포트", "원자재/가격", "안전/ESG"]
}

df_contacts = pd.DataFrame(contacts_data)
df_contacts.to_csv("담당자_명단.csv", index=False, encoding="utf-8-sig")
print("📁 [1단계] '담당자_명단.csv' 파일 생성 완료!")

# -------------------------------------------------------------
df = pd.read_csv("담당자_명단.csv")
print("📋 불러온 담당자 명단:")
print(df[["부서명", "담당자", "수신조건"]])
print("-" * 50)

# -------------------------------------------------------------
# 3. AI 에이전트 이슈 분석 및 분류
# -------------------------------------------------------------
# 테스트해볼 오늘 이슈 (예: 후판 가격 인상 이슈)
today_issue = "HD현대중공업 주요 협력사 B사, 후판 가격 인상으로 인한 원가 부담 증가 및 자금난 호소."

prompt = f"""
당신은 HD현대중공업 동반성장팀 담당자입니다.
아래 이슈를 바탕으로 일일 보고서를 작성하고, 이 이슈가 어떤 분야에 해당하는지 하나만 선택하세요.

[이슈 내용]
{today_issue}

[작성 양식]
1. 분류: [원자재/가격, 안전/ESG, 일반 중 택 1]
2. 요약 및 대책: (3줄 이내)
"""

# Initialize the GenerativeModel after configuring the API key
model = genai.GenerativeModel('gemini-3.6-flash')

response = model.generate_content(
    contents=prompt
)

ai_output = response.text
print("🤖 AI 분석 결과:\n", ai_output)
print("-" * 50)

# -------------------------------------------------------------
# 4. 조건에 맞는 담당자 추출 및 자동 메일 발송
# -------------------------------------------------------------
def send_email(to_email, subject, body):
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain', 'utf-8'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print(f"❌ 메일 발송 오류 ({to_email}): {e}")
        return False

# 분류 키워드 파악
category = "원자재/가격" if "원자재/가격" in ai_output else ("안전/ESG" if "안전/ESG" in ai_output else "일반")

# 엑셀 명단에서 조건이 맞는 부서 사람들만 필터링
target_recipients = df[(df["수신조건"] == "모든리포트") | (df["수신조건"] == category)]

print(f"🎯 이번 이슈('{category}')에 따라 메일을 받을 부서:")

for idx, row in target_recipients.iterrows():
    dept = row["부서명"]
    name = row["담당자"]
    email = row["이메일"]

    email_subject = f"[자동알림] [{dept}] {datetime.now().strftime('%Y-%m-%d')} 협력사 이슈 전달"
    email_body = f"안녕하세요 {name}님 ({dept}),\n\nAI 에이전트가 감지한 맞춤 리포트를 전달합니다.\n\n{ai_output}"

    # 실제 발송
    success = send_email(email, email_subject, email_body)
    if success:
        print(f"✅ [{dept} {name}] ({email}) -> 메일 발송 완료!")
    else:
        print(f"👉 [{dept} {name}] ({email}) -> 메일 발송 실패 (설정을 확인해주세요)!")